---
AWSTemplateFormatVersion: 2010-09-09
Description: Audit Settings

Resources:
  CloudTrail:
    Type: AWS::CloudTrail::Trail
    DependsOn: Bucket
    Properties:
      IncludeGlobalServiceEvents: True
      IsLogging: True
      IsMultiRegionTrail: True
      TrailName: multi-region-logging
      S3BucketName: !Ref Bucket

  Bucket:
    Type: AWS::S3::Bucket
    Properties:
      AccessControl: Private
      BucketName: !Sub cloudtrail-logs-${AWS::AccountId}
      PublicAccessBlockConfiguration:
        BlockPublicAcls: True
        BlockPublicPolicy: True
        IgnorePublicAcls: True
        RestrictPublicBuckets: True

  BucketPolicy:
    Type: AWS::S3::BucketPolicy
    Properties:
      Bucket: !Ref Bucket
      PolicyDocument:
        Statement:
          - Action:
              - S3:GetBucketAcl
            Effect: Allow
            Principal:
              Service: cloudtrail.amazonaws.com
            Resource: !Sub ${Bucket.Arn}
          - Action:
              - S3:PutObject
            Effect: Allow
            Principal: 
              Service: cloudtrail.amazonaws.com
            Resource:
              - !Sub ${Bucket.Arn}/AWSLogs/${AWS::AccountId}/*
            Condition:
              StringEquals:
                s3:x-amz-acl: bucket-owner-full-control